# Kubernetes Deployment — MLOps Iris Classifier
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-iris-ii
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-iris-ii
  template:
    metadata:
      labels:
        app: mlops-iris-ii
    spec:
      containers:
        - name: mlops-iris-ii
          image: us-central1-docker.pkg.dev/sacred-garden-474511-b9/mlops-iris-ii/mlops-iris-ii:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
---
# Kubernetes Service — External Access via LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: mlops-service
spec:
  selector:
    app: mlops-iris-ii
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
